=================================================================== test session starts ====================================================================
platform darwin -- Python 3.10.0b2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/jwr003/coding/pytest-fold, configfile: pyproject.toml, testpaths: tests
plugins: session2file-0.1.11
collecting ... 
collected 18 items                                                                                                                                         

tests/test_pytest_fold.py .F.F.F.FFF...FF..E                                                                                                         [100%]

================================================================= short test summary info ==================================================================
FAILED tests/test_pytest_fold.py::test_which_fails_1 - assert 0
FAILED tests/test_pytest_fold.py::test_which_fails_2 - assert 0
FAILED tests/test_pytest_fold.py::test_which_fails_3 - assert 0
FAILED tests/test_pytest_fold.py::test_fail_1 - assert False
FAILED tests/test_pytest_fold.py::test_fail_2 - assert False
FAILED tests/test_pytest_fold.py::test_fail_3 - assert False
FAILED tests/test_pytest_fold.py::test_which_fails_and_has_stdout_1 - assert 0 == 1
FAILED tests/test_pytest_fold.py::test_which_pauses_and_fails_and_has_stdout_1 - assert 0 == -11
ERROR tests/test_pytest_fold.py::test_fixture_for_fun_fail
=========================================================== [31m[1m8 failed[0m, [32m9 passed[0m, [31m[1m1 error[0m[31m in 2.39s[0m[31m ===========================================================
